#All values are initially set to the maximum possible value that you can enchant.
#You need to configure these to your own needs, otherwise the plugin will do nothing!
maxProt: 4
maxFireProt: 4
maxProjProt: 4
maxSharp: 5
maxFire: 2
maxKB: 2
maxBowPower: 5
maxBowFire: 1
maxBowInfinity: 1
maxBowKB: 2

#Whether enchanting of items which are above values listed above should be allowed
#If not, it will continue until it finds an allowable enchantment.
#(If people do enchant them, they will be removed and downgraded even if this setting is false)
disableEnchanting: false

#Seriously, do not touch this.
configVersionDoNotTouch: 3